apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: idea-fe-deployment
  name: idea-fe-lb-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: idea-fe-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
