apiVersion: v1
kind: Service
metadata:
  labels:
    app: login-manager-deployment
  name: idea-be-lb-svc
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: login-manager-deployment
  type: LoadBalancer

