apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: resource-one-deployment
  name: resource-one-deployment
spec:
  ports:
  - port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: resource-one-deployment
